name : NexusDevelopment
brand : nexusdev.us
description : This is the description of my site
keyword :
url : https://nexusdev.us
email : contact@nexusdev.us
twitter : NexusDevelopment
github : nexusdev
author : nexusdevs
analytics :
year : 2016
markdown : kramdown
exclude :
  - node_modules
