name : Nexus Development
brand : nexusdev.us
description : Decentralized Application R&D Firm
keyword :
url : https://nexusdev.github.io
email : contact@nexusdev.us
twitter : NexusDevelopment
github : NexusDev
author : NexusDev
analytics :
year : 2016
markdown : kramdown
exclude :
  - node_modules
